# Generated by Django 5.0.3 on 2024-04-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
