# Generated by Django 5.0.3 on 2024-04-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0005_rename_address_line2_address_address_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
