# Generated by Django 5.0.3 on 2024-05-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
