# Generated by Django 5.0.3 on 2024-05-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0008_cartitem_total_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
