# Generated by Django 5.0.3 on 2024-05-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0015_alter_orderaddress_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(null=True),
        ),
    ]
