# Generated by Django 5.0.3 on 2024-05-25 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0022_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discounted_price',
        ),
    ]
