# Generated by Django 5.0.3 on 2024-05-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0023_remove_cart_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_coupon_applied',
            field=models.BooleanField(default=False),
        ),
    ]
