# Generated by Django 5.0.3 on 2024-05-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0024_cart_is_coupon_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
