# Generated by Django 5.0.3 on 2024-06-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0029_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reason',
        ),
    ]
